### ISSUE TITLE
Add span catenary model 

### ISSUE THREAD

**Issue by adriengoeller** [phlowers/mechaphlowers#14]
### Describe the expected behavior

Implement an object which can be parametrized with and equation name expecting "catenary", "parabola" and "elastic_catenary'.
The object expose a method z function of x (x coordinate) and p (the sagging parameter)

### Extra Information

Here is a prototype:
```python
class CableDisplay:
    
    
    def __init__(self, display_model):
        self.model_switch = {"parabol":self.z_parabol, "catenary":self.z_catenary, "elastic":self.z_elastic}
        #TODO trycatch
        self.display_model:str = display_model
    
    def z(self, x: float, p: float) -> float:
        return self.model_switch.get(self.display_model, CableDisplay.z_catenary)(x,p)
    
    def z_parabol(x: float, p: float) -> float:
        raise NotImplementedError
    
    def z_elastic(x: float, p: float) -> float:
        raise NotImplementedError
    
    # cable
    @staticmethod
    def z_catenary(x: float, p: float) -> float:
        return p * (np.cosh(x / p) - 1)
```

**Comment by ai-qui** [comment]
As discussed with @adriengoeller we'll rather implement this with an abstract class (named `CableEquation` for example) implemented by 3 different classes, one for each modelization/equation (catenary, parabol and elastic catenary). The abstract class will define a method `z` implemented in each of the 3 subclasses.

Since `x_m` and `x_n` (and probably `L_m` and `L_n`) also depend on the cable equation, it may be interesting to also put them in these classes.

**Comment by ai-qui** [comment]
As discussed with @adriengoeller the abstract class will be named `GeometricCableModel`; for now only the "catenary" will be implemented, with following methods: `z`, `x_m` and `x_n`.
`span_length`, `elevation_difference` and `p` will be given at Model initialization.

**Comment by ai-qui** [comment]
Up-to-date link for the documentation: https://phlowers.readthedocs.io/projects/mechaphlowers/en/latest/user_guide/ug_cable_model.html
